from rest_framework import serializers

from apps.detection.models import Threat


class ThreatSerializer(serializers.ModelSerializer):
    """API serializer for threat records generated by detection pipeline."""

    class Meta:
        model = Threat
        fields = (
            "id",
            "security_log",
            "threat_level",
            "threat_type",
            "confidence_score",
            "detected_at",
            "message",
            "reason",
            "analysis_payload",
            "created_at",
            "updated_at",
        )
