from rest_framework import serializers

from apps.detection.models import Threat


class ThreatSerializer(serializers.ModelSerializer):
    """API serializer for threat records generated by detection pipeline."""

    file_path = serializers.CharField(source="security_log.file_path", read_only=True)
    process_name = serializers.SerializerMethodField()
    source_ip = serializers.SerializerMethodField()
    behavior_pattern = serializers.SerializerMethodField()
    encryption_type = serializers.SerializerMethodField()

    def _payload(self, obj: Threat) -> dict:
        return obj.analysis_payload or {}

    def _metadata(self, obj: Threat) -> dict:
        return obj.security_log.metadata or {}

    def get_process_name(self, obj: Threat):
        return (
            self._payload(obj).get("process_name")
            or self._metadata(obj).get("process_name")
            or "unknown"
        )

    def get_source_ip(self, obj: Threat):
        return self._payload(obj).get("source_ip") or self._metadata(obj).get("source_ip") or ""

    def get_behavior_pattern(self, obj: Threat):
        matches = self._payload(obj).get("rule_matches") or []
        if matches:
            return "; ".join(matches)
        return self._payload(obj).get("behavior_pattern") or obj.reason or ""

    def get_encryption_type(self, obj: Threat):
        entropy = self._payload(obj).get("entropy") or self._metadata(obj).get("entropy")
        if entropy and float(entropy) > 7.0:
            return "High-entropy content (possible encryption)"
        return self._payload(obj).get("encryption_type") or "Not determined"

    class Meta:
        model = Threat
        fields = (
            "id",
            "security_log",
            "threat_level",
            "threat_type",
            "confidence_score",
            "detected_at",
            "message",
            "reason",
            "analysis_payload",
            "file_path",
            "process_name",
            "source_ip",
            "behavior_pattern",
            "encryption_type",
            "created_at",
            "updated_at",
        )
