from rest_framework import serializers

from apps.detection.models import Threat


class ThreatSerializer(serializers.ModelSerializer):
    """API serializer for threat records generated by detection pipeline."""

    file_path = serializers.CharField(source="security_log.file_path", read_only=True)
    process_name = serializers.SerializerMethodField()
    source_ip = serializers.SerializerMethodField()
    behavior_pattern = serializers.SerializerMethodField()
    encryption_type = serializers.SerializerMethodField()

    def _payload(self, obj: Threat) -> dict:
        return obj.analysis_payload or {}

    def _metadata(self, obj: Threat) -> dict:
        return obj.security_log.metadata or {}

    def get_process_name(self, obj: Threat):
        return self._payload(obj).get("process_name") or self._metadata(obj).get("process_name") or "demo_simulation"

    def get_source_ip(self, obj: Threat):
        return self._payload(obj).get("source_ip") or "198.51.100.23"

    def get_behavior_pattern(self, obj: Threat):
        return self._payload(obj).get("behavior_pattern") or "Rapid file modifications and rename sequence"

    def get_encryption_type(self, obj: Threat):
        return self._payload(obj).get("encryption_type") or "Fernet (AES-based) - Simulated"

    class Meta:
        model = Threat
        fields = (
            "id",
            "security_log",
            "threat_level",
            "threat_type",
            "confidence_score",
            "detected_at",
            "message",
            "reason",
            "analysis_payload",
            "file_path",
            "process_name",
            "source_ip",
            "behavior_pattern",
            "encryption_type",
            "created_at",
            "updated_at",
        )
