# Generated by Django 5.2.13 on 2026-04-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threat_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=16)),
                ('confidence_score', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('security_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='detection.securitylog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='alert',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='detection.threat'),
        ),
        migrations.DeleteModel(
            name='DetectedThreat',
        ),
    ]
