# Generated by Django 5.2.13 on 2026-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_threat_alter_alert_threat_delete_detectedthreat'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='action',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='file_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='threat',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(default='Normal', max_length=64),
        ),
    ]
