# Generated by Django 5.2.13 on 2026-07-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_securitylog_action_securitylog_file_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=128)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('status_code', models.IntegerField(default=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_vector', models.JSONField(default=dict)),
                ('feature_names', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='HashRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('ai_score', models.FloatField(default=0.0)),
                ('rule_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('prediction_latency_ms', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pid', models.IntegerField(default=0)),
                ('process_name', models.CharField(blank=True, max_length=255)),
                ('executable_path', models.CharField(blank=True, max_length=1024)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('parent_pid', models.IntegerField(default=0)),
                ('cmdline', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='detection_a_created_9e73b2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='detection_a_status_930b13_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['-created_at'], name='detection_s_created_2fc407_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['source', 'action'], name='detection_s_source_4c5c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['file_path'], name='detection_s_file_pa_b6069b_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['-detected_at'], name='detection_t_detecte_66ec35_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['threat_level'], name='detection_t_threat__bc1df8_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featurerecord',
            name='security_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_records', to='detection.securitylog'),
        ),
        migrations.AddIndex(
            model_name='hashrecord',
            index=models.Index(fields=['label'], name='detection_h_label_2ee95c_idx'),
        ),
        migrations.AddField(
            model_name='modelprediction',
            name='security_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='detection.securitylog'),
        ),
        migrations.AddField(
            model_name='modelprediction',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='detection.threat'),
        ),
        migrations.AddField(
            model_name='processrecord',
            name='security_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_records', to='detection.securitylog'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='detection_a_created_c17532_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='detection_a_action_a3be85_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerecord',
            index=models.Index(fields=['-created_at'], name='detection_f_created_3d5718_idx'),
        ),
        migrations.AddIndex(
            model_name='modelprediction',
            index=models.Index(fields=['-created_at'], name='detection_m_created_05be3f_idx'),
        ),
        migrations.AddIndex(
            model_name='modelprediction',
            index=models.Index(fields=['model_name'], name='detection_m_model_n_d49067_idx'),
        ),
        migrations.AddIndex(
            model_name='processrecord',
            index=models.Index(fields=['pid'], name='detection_p_pid_18b808_idx'),
        ),
        migrations.AddIndex(
            model_name='processrecord',
            index=models.Index(fields=['process_name'], name='detection_p_process_b46133_idx'),
        ),
    ]
