# Generated by Django 5.2.13 on 2026-04-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0002_threat_alter_alert_threat_delete_detectedthreat'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoneypotAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(blank=True, max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('security_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honeypot_hits', to='detection.securitylog')),
                ('honeypot_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='deception.honeypotfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('honeypot_file', 'security_log'), name='unique_honeypot_hit_per_log')],
            },
        ),
    ]
