# Generated by Django 5.2.13 on 2026-04-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deception', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeypotfile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='honeypotfile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='honeypotfile',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HoneypotAccessEvent',
        ),
    ]
